### ISSUE TITLE
NMMNH Mammals - records from MSB

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/data-migration#197] opened 2020-01-29 15:07 UTC
Download all MSB records with NMMNH catalog number associated.

**Comment by Jegelewicz** [comment] 2020-01-29 15:11
@dustymc I need to get [these](https://arctos.database.museum/saved/MSB%5FMamm%5Fwith%5FNMMNH%5Fnumber) downloaded for the bulkloader so that we can create the NMMNH records for the parts that are at NMMNH but when I try that I get a timeout error. Can you get them for us?

**Comment by dustymc** [comment] 2020-01-29 16:04
Apparently not easily. I've upped the timeout on the download to "might kill something" levels, that's apparently not sufficient. Can you try smaller batches? If not I can look for another solution, but perhaps not immediately. Please let me know when you're done and I'll reset the download timeout, hopefully before it becomes a problem.

FWIW this is one of the many places where the bill for our proliferation of attributes comes due.

**Comment by Jegelewicz** [comment] 2020-01-29 16:29
> FWIW this is one of the many places where the bill for our proliferation of attributes comes due.

Perhaps I will download without any attributes, then bulkload attributes later - but I'll need a way to get them from the MSB records....

**Comment by dustymc** [comment] 2020-01-29 16:43
I can help with that (or give you the SQL), I'll just need a list of GUIDs (column in a table or CSV is ideal) - dealing with attriubtes vertically isn't much problem, shifting them to horizontal and trying to extract column names from data and such is.

I intend to JSONify attributes in PG, so eventually (hopefully soonish) that might be less of a problem, at least for anything that can deal with complex JSON data.

**Comment by Jegelewicz** [comment] 2020-01-29 17:04
> shifting them to horizontal and trying to extract column names from data and such is.

Nah - it's not that hard.

**Comment by dustymc** [comment] 2020-01-29 17:11
Oracle thinks it is! Hopefully PG can be convinced otherwise....

**Comment by Jegelewicz** [comment] 2020-01-29 17:33
That is what Excel is for....

**Comment by dustymc** [comment] 2020-01-29 17:37
Sounds like a mini-tutorial waiting to happen!

**Comment by Jegelewicz** [comment] 2020-01-29 18:09
Sheesh!

**Comment by Jegelewicz** [comment] 2020-01-30 00:08
FYI my request for the bulkloader ready download ran all day - I just shut it down because I am going home. I'll try splitting it up or something else tomorrow.
/remind me to do this tomorrow

**Comment by dustymc** [comment] 2020-01-30 01:49
>ran all day 

More likely your browser wandered off - looks like it (or something...) completed, here's the file.

[download_4_bulkloader(5).csv.zip](https://github.com/ArctosDB/data-migration/files/4131765/download_4_bulkloader.5.csv.zip)

**Comment by Jegelewicz** [comment] 2020-01-30 16:39
@lin-fred I've taken this download and prepped it for bulkloading. There are some records with too many other ID's, some with too many parts, and some with too many identifications, but we can get those extras later and load them separately.

The file is here: N:\BioScience\Arctos and it is called MSB Mammal bulkload

If all of the accessions are in Arctos, this should load - of course I could have missed something else (and probably did), but I think you caould have these loaded by the end of the day tomorrow if you want!

**Comment by lin-fred** [comment] 2020-01-31 21:37
Uploaded, working on fixing a few errors and working on getting the non-tissued mammals uploaded

**Comment by Jegelewicz** [comment] 2020-03-23 20:30
@lin-fred I had a chat with Mariel today and realized that all the MSB identifiers in the NMMNH records were uploaded with the relationship "self". I removed those and added identifiers with the relationship "same individual as" today so that appropriate links will be created and users at GBIF will be able to see the relationship.

**Comment by lin-fred** [comment] 2020-03-23 21:51
Thanks all for catching that, and thanks Teresa for getting it fixed

I am also good with your barcode solution

**Comment by campmlc** [comment] 2020-03-24 00:59
Thank you!

**Comment by Jegelewicz** [comment] 2020-03-24 14:10
> Having the barcodes associated with tissues in both collections causes problems for loans and for specimen counts on Mariel's side of the ledger. Our solution is to give all of the NMMNH frozen tissues a new barcode. I propose we create a building and give the barcode the label "Museum of Southwestern Biology, Division of Genomic Resources". That way, all of the tissues that are at MSB (and we know they are there because they have been given an MSB Barcode), will appear to everyone as "at MSB DGR".

@dustymc if I send you a file with part numbers, old container barcode and new container barcode, could you put all of these parts into the new container? I'm talking thousands of parts here or else I would do it manually.

**Comment by dustymc** [comment] 2020-03-24 14:17
Depends what you mean by "part numbers" - if you give me something I can find the part, and not find other parts, plus a new immediate parent container, sure.

I'm pretty baffled by what you're trying to DO though - you're going to denormalize a BUILDING and everything in it because ?????????????????????????????????? If you'd care to explain, I might be able to suggest a less "...and then DGR eats 5 years of your life, and the data are still crap!"-like solution.

**Comment by campmlc** [comment] 2020-03-24 14:40
I would suggest not using DGR's full title in your container name (e.g.
denormalization). This will not be publicly available, and shorter is way
better than longer in container labels when you are trying to download a
csv. Why not "Transferred to MSB"?

**Comment by Jegelewicz** [comment] 2020-03-24 14:40
Here is the issue:

NMMNH:Mamm had a bunch of frozen tissues and a precarious freezer.

In 2012, NMMNH:Mamm and some other miscellaneous frozen samples were sent to MSB

MSB cataloged all of the NMMNH mammals (skins, skeletons, tissues - everything whether they had it or not). They also barcoded the tissues (mostly) and put a lot of them in nitrogen.

Between the time this happened and NMMNH decision to join Arctos, there was a complete turnover in NMMNH staff and as far as NMMNH administration is concerned there is no signed agreement for what happened (the transaction was never approved by the NMMNH Board - required by NMMNH standards). Also, nobody took an inventory of what actually went to MSB and what stayed at NMMNH (some skins and skeletons went, some didn't).

This past fall, I was assigned the task of migrating NMMNH Mammals into Arctos. @lin-fred and I downloaded the MSB records did some reconfiguration and uploaded them as NMMNH records with appropriate relationships (OK they are appropriate after I corrected them yesterday). In this process, I left the barcodes attached to the tissues so that now if you look up any of these barcodes you see both an MSB and an NMMNH part. Much to @campmlc dismay, when she attempts to get counts of specimens in her freezers, she is now double counting these specimens.

I have gone back and forth about this, but the real problem is that the two institutions don't agree on what is going on with this relationship. NMMNH thinks these are their specimens and MSB thinks they are now theirs. They are accessioned in both places (makes my museum mind explode) and both expect to get "credit" for use of the stuff. Without a clear understanding of what this transaction really was (a deaccession and transfer of custody or a custodial agreement) I really don't know the final course of action and no matter what we do now, it may need to be reversed later when (if) the appropriate people from these two institutions sit down together.

The solution proposed by @campmlc is that we remove the MSB barcodes from the NMMNH parts (but leave them on the MSB parts) and add a barcode to all of the NMMNH parts that allows @lin-fred to know where they are (the MSB building). I am not 100% happy with this, but it seems workable for both of them and I am tired of dealing with something that I cannot fix, so if I can make them happy, that's all I can hope for.

**Comment by dustymc** [comment] 2020-03-24 14:51
>DGR's full title in your container name (e.g. denormalization)

The problem is with having two data objects representing one entity, the name isn't important.

>and a precarious freezer

As all good stories start!

So there's one physical THING and some politics, right? You're not doing some crazy thing involving two THINGS in the same place but claiming something else? If that's the jist, then it's probably just a mess, and putting the fake things in another fake thing seems as good as anything.

**Comment by Jegelewicz** [comment] 2020-03-24 14:59
> So there's one physical THING and some politics, right? 

Exactly

> You're not doing some crazy thing involving two THINGS in the same place but claiming something else?

Correct.

> If that's the jist, then it's probably just a mess, and putting the fake things in another fake thing seems as good as anything.

Cool. I'll work up the file and try to get it to you by the end of the day. I plan to use the Part ID from a specimen download so you know which part is being given the new barcode.

**Comment by Jegelewicz** [comment] 2020-03-24 22:22
@dustymc this file has three columns, the Part ID number, the old barcode and the new barcode. Let me know if you need a different format.
[MSB Barcodes.zip](https://github.com/ArctosDB/data-migration/files/4377912/MSB.Barcodes.zip)

**Comment by dustymc** [comment] 2020-03-24 23:11
done

**Comment by Jegelewicz** [comment] 2020-05-07 22:46
@dustymc can we do [this](https://github.com/ArctosDB/data-migration/issues/197#issuecomment-603535677) again - it was lost in the missing month of Arctos.

**Comment by Jegelewicz** [comment] 2020-05-07 22:47
OOF - I probably need to create the barcode...

**Comment by Jegelewicz** [comment] 2020-05-07 22:49
OK that part is done.

**Comment by lin-fred** [comment] 2020-05-07 22:58
Thanks for doing it again! You have no idea how much I appreciate it!

**Comment by dustymc** [comment] 2020-05-07 23:13
Done. Here's the code because it took me a while to find it....

```
create table temp_nm_part as select * from dlm.my_temp_cf;
select * from temp_nm_part where PART_ID not in (select collection_object_id from specimen_part);

no rows selected


select guid_prefix , count(*) from collection,cataloged_item,specimen_part,temp_nm_part where collection.collection_id=cataloged_item.collection_id and cataloged_item.collection_object_id=specimen_part.derived_from_cat_item and specimen_part.collection_object_id=temp_nm_part.PART_ID
group by guid_prefix;


GUID_PREFIX						       COUNT(*)
------------------------------------------------------------ ----------
NMMNH:Mamm							   7920


alter table temp_nm_part add cid number;

update temp_nm_part set cid=(select container_id from coll_obj_cont_hist where coll_obj_cont_hist.collection_object_id=temp_nm_part.part_id);

select * from 	temp_nm_part where cid is null;


alter table temp_nm_part add ncid number;

update temp_nm_part set ncid=(select container_id from container where container.barcode=temp_nm_part.BARCODE_NEW);

select * from 	temp_nm_part where ncid is null;

exec pause_maintenance('off');


-- please don't explode please don't explode please don't explode....
alter table temp_nm_part add gotit number;

begin
 for r in (select * from temp_nm_part where gotit is null and rownum < 1000) loop
 	update container set parent_container_id=r.ncid where container_id=r.cid;
 	update temp_nm_part set gotit=1 where cid=r.cid;
 end loop;
end;
/


select * from temp_nm_part where gotit is null;

no rows selected

-- oh yeah it didn't explode

commit;

exec pause_maintenance('on');


```

**Comment by Jegelewicz** [comment] 2020-05-07 23:25
Thanks!

**Comment by lin-fred** [comment] 2020-05-07 23:37
Thank you!

**Comment by campmlc** [comment] 2020-05-08 00:00
Yes, me too!

**Comment by campmlc** [comment] 2020-05-08 00:01
Is " please don't explode" magic code?
:)

**Comment by dustymc** [comment] 2020-05-08 00:20
seems to have worked, I'm going with "yes"

**Closed** 2020-05-15 17:10 UTC
