### ISSUE TITLE
3. NMMNH Birds - Agents

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/data-migration#26] opened 2019-03-25 22:12 UTC
Read the documentation about [Agents](http://handbook.arctosdb.org/documentation/agent.html).

Create a list of people included in the data to be migrated in a .csv file (Excel will work fine for this). Look in fields where you store the names of collectors, preparators, donors, publication authors, etc.

Review the list for alternate spellings and versions of "unknown" (names that are only initials or include only initials plus last name). Try to make each name as complete as possible and to ensure that there are no duplicates. Don't lose the original spellings/abbreviations as you will need to ensure they are either part of an Agent or are modified in your data to match an Agent name before you load your data.

Use the csv in the Agent BUlkload tool to find out which names in your list need to be added to Arctos Agents.

from the Arctos main menu select Enter Data > Batch Tools > Bulkload Agents and follow the instructions

**Comment by Jegelewicz** [comment] 2019-03-25 22:25
See conversation in #1

**Comment by lin-fred** [comment] 2019-04-01 18:17
I have my first batch of agents to be bulkloaded.  Do I need to send the CSV to someone? The Bulkloader states: Non-fatal errors have been detected. A member of the Arctos Advisory Committee can force-load these data. Please keep the following in mind. Further documentation is available here.

**Comment by campmlc** [comment] 2019-04-01 18:37
Hi Lindsey, you can send the file to me and I'll look it over.

**Comment by campmlc** [comment] 2019-04-01 19:40
Agents have loaded. Let me know if you find any issues.

**Comment by lin-fred** [comment] 2019-04-02 17:23
I have another file of Agents to be uploaded if someone is available to push it through. Thanks

**Comment by campmlc** [comment] 2019-04-02 17:28
I am available - send it on through!

**Comment by lin-fred** [comment] 2019-04-02 18:25
@dustymc I noticed a duplicate agent that slipped through. We bulkloaded a John Hafner, who I think is probably the same as John C. Hafner but it said there was "no problems detected".

**Comment by dustymc** [comment] 2019-04-02 18:44
http://handbook.arctosdb.org/documentation/agent.html#deletingmerging-agents

That would not have been detected because John C. has J. as a first name. I can only work with the data provided!

**Comment by lin-fred** [comment] 2019-04-02 18:59
This is true. That means John C. Hafner should also have an updated first name? Should I do that or should someone from MSB since it's originally an MSB agent? I'll be adding a "aka" so that NMMNHS data can get uploaded to him correctly.

**Comment by campmlc** [comment] 2019-04-02 19:05
Lindsey, if they are clearly duplicates ( and you'd want to look at agent
activity to be sure) you can marked one as a bad duplicate of they other to
merge them.

**Comment by dustymc** [comment] 2019-04-02 19:30
Yes, please update that sort of thing when you encounter it - that's one of the core benefits to the shared system.

I don't think adding an AKA is ever a problem - it just makes the record more discoverable.

Adding a "bad duplicate of" relationship requires something closer to reasonable suspicion than certainty. The relationship triggers emails to everyone using the agent, so the group can respond (eg, by removing the 'bad duplicate' and adding a 'not the same as' relationship) if they are not duplicates. The original data are preserved as attribute 'verbatim collector' so there should be no loss even if the agent is incorrectly merged and eventually re-split.

**Comment by lin-fred** [comment] 2019-04-10 17:58
I ran into another agent where the preferred name had the first and last but the agent table only listed the first name as an initial, and so the bulkloader didn't catch it. This one is Carol K. Malcolm and a duplicate was created. 

Can the bulkload for this look at the last names? And then give the options of possible duplicates? Or would that cause too many "FATAL ERROR: duplicate of" statuses? Like if you have a C. Malcolm and a Carol Malcolm, they don't seem to connect or do they?

I'm going to go through each agent individually that has been uploaded and check on them, I'm getting the feeling some more probably slipped through.

**Comment by dustymc** [comment] 2019-04-10 18:12
That should be filed as a new Issue. I'm definitely up for a more-paranoid agent loader, but I'm only one user (and the one who can avoid the loader if necessary....).

The checker can do anything the data support, but I suspect this would just be an overwhelming number of potential matches and giant globs of data tend to not be useful - humans just can't process them efficiently.

I'd probably make C. and Carol bad dups of Carol K in this case - I don't see any obvious reason they're not, and the folks in those collections will get the notifications a couple weeks before anything (which includes saving the originals as verbatim collectors) happens.

**Comment by lin-fred** [comment] 2019-04-10 19:19
I guess I assumed the bulkloader checked on just the last name if it needed to, but it checks on both the last and first as a minimum? Is this correct?

I can see how it could get out of hand with some names if it checks on last name, but at the same time I'd rather it tell me it's a possible duplicate of 15 names than tell me it's not a duplicate at all. 

Currently, it seems the bulkloader tool can be used when assuming the agents in Arctos are all perfect and ready for new collections to upload their data, but this is of course not the case.

Should this be part of  ArctosDB/arctos#1612 or should it be a new issue discussion?

**Comment by campmlc** [comment] 2019-04-10 20:04
Maybe we need the option of a more stringent search available in the
prebulkloader tool, so we can choose the level of specificity of the match
from last name only to first and last or first last and middle initial?
Lindsey, just be careful to check any potential duplicates based on their
sources, dates, and agent activity before assuming two names are the same.
J. Smith from 1965 at UAM  is probably not the same as John Smith from MSB
Mamm in 2007.

**Comment by Jegelewicz** [comment] 2019-04-11 16:29
> Currently, it seems the bulkloader tool can be used when assuming the agents in Arctos are all perfect and ready for new collections to upload their data, but this is of course not the case.

Yep and it will probably never be the case. There will always be missing aka's from agent names that mean the Agent bulkloader won't catch dupes.

It really isn't a big deal because once you discover the duplication, as Dusty says you can mark one as a bad duplicate of the one you want to keep and they will be merged and all records using the bad name will get the good one.

And as Dusty points out, putting J. Smith in the tool will return a whole mess of potential duplicates that you would need to weed through and I'm not sure that would be the most effective use of your time! We have bounced around the idea of an Agents committee and even started a [GitHub project](https://github.com/ArctosDB/arctos/projects/11) for it but no one has picked up the challenge. If this becomes near and dear to you, perhaps you would like to lead the committee? :-)

**Comment by lin-fred** [comment] 2019-04-11 16:46
So when the bad duplicate gets merged with the correct one, all the connections it had gets moved along as well correct?

**Comment by Jegelewicz** [comment] 2019-04-11 16:52
Yep!

**Comment by dustymc** [comment] 2019-04-11 17:24
yes

**Comment by Jegelewicz** [comment] 2019-04-11 20:51
BTW - you can also run reports to look for dupes and such at http://arctos.database.museum/info/dupAgent.cfm

**Closed** 2019-05-15 21:21 UTC
